sudo: false  # Use container-based infrastructure
language: node_js
node_js:
  - "0.12"

script: >
    npm run build &&
    ./scripts/post_code_size.py dist/pileup.min.js &&
    npm run test &&
    npm run flow-check &&
    npm run lint &&
    npm run coverage &&
    ./scripts/post-coverage.sh
